// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShowroomCar.Infrastructure.Persistence.Entities;

#nullable disable

namespace ShowroomCar.Infrastructure.Migrations
{
    [DbContext(typeof(ShowroomDbContext))]
    [Migration("20251110100440_InitModel")]
    partial class InitModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_unicode_ci")
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GoodsReturn", b =>
                {
                    b.Property<long>("GrtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("GrtId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GrtNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("PoId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("ReturnDate")
                        .HasColumnType("date");

                    b.Property<long>("SupplierId")
                        .HasColumnType("bigint");

                    b.HasKey("GrtId");

                    b.ToTable("GoodsReturns");
                });

            modelBuilder.Entity("GoodsReturnItem", b =>
                {
                    b.Property<long>("GrtItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("GrtItemId"));

                    b.Property<long>("GrtId")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("VehicleId")
                        .HasColumnType("bigint");

                    b.HasKey("GrtItemId");

                    b.HasIndex("GrtId");

                    b.ToTable("GoodsReturnItems");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.Allotment", b =>
                {
                    b.Property<long>("AllotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("allot_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("AllotId"));

                    b.Property<DateTime?>("ReservedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("reserved_at");

                    b.Property<long>("SoId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("so_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<long>("VehicleId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("vehicle_id");

                    b.HasKey("AllotId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SoId" }, "fk_allot_so");

                    b.HasIndex(new[] { "VehicleId" }, "vehicle_id")
                        .IsUnique();

                    b.ToTable("allotments", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("action");

                    b.Property<long?>("ActorUserId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("Changes")
                        .HasColumnType("json")
                        .HasColumnName("changes");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("entity");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("entity_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ActorUserId" }, "fk_audit_user");

                    b.ToTable("audit_logs", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("brand_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BrandId"));

                    b.Property<string>("Country")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("country");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("BrandId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Name" }, "name")
                        .IsUnique();

                    b.ToTable("brands", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.Customer", b =>
                {
                    b.Property<long>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("customer_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("CustomerId"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("IdNo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("id_no");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("CustomerId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Code" }, "code")
                        .IsUnique();

                    b.ToTable("customers", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.Document", b =>
                {
                    b.Property<long>("DocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("doc_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("DocId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("created_by");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("customer_id");

                    b.Property<DateOnly>("DocDate")
                        .HasColumnType("date")
                        .HasColumnName("doc_date");

                    b.Property<string>("DocNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("doc_no");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("doc_type");

                    b.Property<long?>("RelatedId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("related_id");

                    b.Property<string>("RelatedTable")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("related_table");

                    b.Property<string>("StorageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_url");

                    b.HasKey("DocId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DocNo" }, "doc_no")
                        .IsUnique();

                    b.HasIndex(new[] { "CustomerId" }, "fk_doc_customer");

                    b.HasIndex(new[] { "CreatedBy" }, "fk_doc_user");

                    b.ToTable("documents", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.DocumentLink", b =>
                {
                    b.Property<long>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("link_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("LinkId"));

                    b.Property<long>("DocId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("doc_id");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityTable")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("entity_table");

                    b.HasKey("LinkId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "DocId" }, "fk_doclink_doc");

                    b.ToTable("document_links", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.GoodsReceipt", b =>
                {
                    b.Property<long>("GrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("gr_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("GrId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("created_by");

                    b.Property<string>("GrNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("gr_no");

                    b.Property<long?>("PoId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("po_id");

                    b.Property<DateOnly>("ReceiptDate")
                        .HasColumnType("date")
                        .HasColumnName("receipt_date");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int(11)")
                        .HasColumnName("warehouse_id");

                    b.HasKey("GrId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PoId" }, "fk_gr_po");

                    b.HasIndex(new[] { "CreatedBy" }, "fk_gr_user");

                    b.HasIndex(new[] { "WarehouseId" }, "fk_gr_wh");

                    b.HasIndex(new[] { "GrNo" }, "gr_no")
                        .IsUnique();

                    b.ToTable("goods_receipts", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.GoodsReceiptItem", b =>
                {
                    b.Property<long>("GrItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("gr_item_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("GrItemId"));

                    b.Property<long>("GrId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("gr_id");

                    b.Property<decimal?>("LandedCost")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("landed_cost")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<long>("VehicleId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("vehicle_id");

                    b.HasKey("GrItemId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "GrId" }, "fk_gri_gr");

                    b.HasIndex(new[] { "VehicleId" }, "vehicle_id")
                        .IsUnique()
                        .HasDatabaseName("vehicle_id1");

                    b.ToTable("goods_receipt_items", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.InventoryMove", b =>
                {
                    b.Property<long>("MoveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("move_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("MoveId"));

                    b.Property<int?>("FromWarehouseId")
                        .HasColumnType("int(11)")
                        .HasColumnName("from_warehouse_id");

                    b.Property<DateTime?>("MovedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("moved_at");

                    b.Property<long?>("MovedBy")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("moved_by");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("reason");

                    b.Property<int?>("ToWarehouseId")
                        .HasColumnType("int(11)")
                        .HasColumnName("to_warehouse_id");

                    b.Property<long>("VehicleId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("vehicle_id");

                    b.HasKey("MoveId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "FromWarehouseId" }, "fk_inventory_moves_from_wh");

                    b.HasIndex(new[] { "ToWarehouseId" }, "fk_inventory_moves_to_wh");

                    b.HasIndex(new[] { "MovedBy" }, "fk_inventory_moves_user");

                    b.HasIndex(new[] { "VehicleId" }, "fk_inventory_moves_vehicle");

                    b.ToTable("inventory_moves", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.Invoice", b =>
                {
                    b.Property<long>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("invoice_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("InvoiceId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("created_by");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("customer_id");

                    b.Property<decimal>("Discount")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("discount");

                    b.Property<decimal>("GrandTotal")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("grand_total");

                    b.Property<DateOnly>("InvoiceDate")
                        .HasColumnType("date")
                        .HasColumnName("invoice_date");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("invoice_no");

                    b.Property<long?>("SoId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("so_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Tax")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("tax");

                    b.HasKey("InvoiceId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CustomerId" }, "fk_inv_customer");

                    b.HasIndex(new[] { "SoId" }, "fk_inv_so");

                    b.HasIndex(new[] { "CreatedBy" }, "fk_inv_user");

                    b.HasIndex(new[] { "InvoiceNo" }, "invoice_no")
                        .IsUnique();

                    b.ToTable("invoices", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.InvoiceItem", b =>
                {
                    b.Property<long>("InvItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("inv_item_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("InvItemId"));

                    b.Property<decimal?>("Discount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("discount")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("invoice_id");

                    b.Property<decimal?>("LineTotal")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("line_total");

                    b.Property<decimal?>("Tax")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("tax")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("unit_price");

                    b.Property<long>("VehicleId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("vehicle_id");

                    b.HasKey("InvItemId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "InvoiceId" }, "fk_invi_inv");

                    b.HasIndex(new[] { "VehicleId" }, "fk_invi_vehicle");

                    b.ToTable("invoice_items", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.Payment", b =>
                {
                    b.Property<long>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("payment_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("amount");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("customer_id");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("method");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("payment_date");

                    b.Property<string>("ReceiptNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("receipt_no");

                    b.HasKey("PaymentId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CustomerId" }, "fk_pay_customer");

                    b.HasIndex(new[] { "ReceiptNo" }, "receipt_no")
                        .IsUnique();

                    b.ToTable("payments", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.PaymentAllocation", b =>
                {
                    b.Property<long>("AllocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("alloc_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("AllocId"));

                    b.Property<decimal>("AmountApplied")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("amount_applied");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("invoice_id");

                    b.Property<long>("PaymentId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("payment_id");

                    b.HasKey("AllocId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "InvoiceId" }, "fk_alloc_invoice");

                    b.HasIndex(new[] { "PaymentId" }, "fk_alloc_pay");

                    b.ToTable("payment_allocations", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.PurchaseOrder", b =>
                {
                    b.Property<long>("PoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("po_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("PoId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date")
                        .HasColumnName("order_date");

                    b.Property<string>("PoNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("po_no");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int(11)")
                        .HasColumnName("supplier_id");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("total_amount");

                    b.HasKey("PoId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SupplierId" }, "fk_po_supplier");

                    b.HasIndex(new[] { "CreatedBy" }, "fk_po_user");

                    b.HasIndex(new[] { "PoNo" }, "po_no")
                        .IsUnique();

                    b.ToTable("purchase_orders", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.PurchaseOrderItem", b =>
                {
                    b.Property<long>("PoItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("po_item_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("PoItemId"));

                    b.Property<decimal?>("LineTotal")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("line_total");

                    b.Property<int>("ModelId")
                        .HasColumnType("int(11)")
                        .HasColumnName("model_id");

                    b.Property<long>("PoId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("po_id");

                    b.Property<int>("Qty")
                        .HasColumnType("int(11)")
                        .HasColumnName("qty");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("PoItemId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ModelId" }, "fk_poi_model");

                    b.HasIndex(new[] { "PoId" }, "fk_poi_po");

                    b.ToTable("purchase_order_items", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.Quotation", b =>
                {
                    b.Property<long>("QuoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("quote_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("QuoteId"));

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("created_by");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("customer_id");

                    b.Property<decimal>("Discount")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("discount");

                    b.Property<decimal>("GrandTotal")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("grand_total");

                    b.Property<DateOnly>("QuoteDate")
                        .HasColumnType("date")
                        .HasColumnName("quote_date");

                    b.Property<string>("QuoteNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("quote_no");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Tax")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("tax");

                    b.HasKey("QuoteId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CustomerId" }, "fk_quote_customer");

                    b.HasIndex(new[] { "CreatedBy" }, "fk_quote_user");

                    b.HasIndex(new[] { "QuoteNo" }, "quote_no")
                        .IsUnique();

                    b.ToTable("quotations", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.QuotationItem", b =>
                {
                    b.Property<long>("QuoteItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("quote_item_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("QuoteItemId"));

                    b.Property<decimal?>("LineTotal")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("line_total");

                    b.Property<int>("ModelId")
                        .HasColumnType("int(11)")
                        .HasColumnName("model_id");

                    b.Property<int>("Qty")
                        .HasColumnType("int(11)")
                        .HasColumnName("qty");

                    b.Property<long>("QuoteId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("quote_id");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("QuoteItemId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ModelId" }, "fk_qi_model");

                    b.HasIndex(new[] { "QuoteId" }, "fk_qi_quote");

                    b.ToTable("quotation_items", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("role_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("RoleId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Code" }, "code")
                        .IsUnique()
                        .HasDatabaseName("code1");

                    b.ToTable("roles", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.SalesOrder", b =>
                {
                    b.Property<long>("SoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("so_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("SoId"));

                    b.Property<long?>("AssignedTo")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("assigned_to");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("created_by");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("customer_id");

                    b.Property<decimal>("Discount")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("discount");

                    b.Property<decimal>("GrandTotal")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("grand_total");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date")
                        .HasColumnName("order_date");

                    b.Property<string>("SoNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("so_no");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Tax")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("tax");

                    b.HasKey("SoId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "AssignedTo" }, "fk_so_assigned_to");

                    b.HasIndex(new[] { "CreatedBy" }, "fk_so_created_by");

                    b.HasIndex(new[] { "CustomerId", "Status", "OrderDate" }, "ix_so_cust_status_date");

                    b.HasIndex(new[] { "SoNo" }, "so_no")
                        .IsUnique();

                    b.ToTable("sales_orders", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.SalesOrderItem", b =>
                {
                    b.Property<long>("SoItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("so_item_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("SoItemId"));

                    b.Property<decimal?>("Discount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("discount")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<decimal?>("LineTotal")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("line_total");

                    b.Property<decimal>("SellPrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("sell_price");

                    b.Property<long>("SoId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("so_id");

                    b.Property<decimal?>("Tax")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("tax")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<long>("VehicleId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("vehicle_id");

                    b.HasKey("SoItemId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SoId" }, "fk_soi_so");

                    b.HasIndex(new[] { "VehicleId" }, "vehicle_id")
                        .IsUnique()
                        .HasDatabaseName("vehicle_id2");

                    b.ToTable("sales_order_items", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.ServiceOrder", b =>
                {
                    b.Property<long>("SvcId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("svc_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("SvcId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("created_by");

                    b.Property<long>("GrId")
                        .HasColumnType("bigint");

                    b.Property<long>("ModelId")
                        .HasColumnType("bigint");

                    b.Property<int>("ModelId1")
                        .HasColumnType("int(11)");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<long>("PoId")
                        .HasColumnType("bigint");

                    b.Property<int>("QuantityExpected")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ScheduledDate")
                        .HasColumnType("date")
                        .HasColumnName("scheduled_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("SvcNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("svc_no");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("VehicleId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("vehicle_id");

                    b.HasKey("SvcId")
                        .HasName("PRIMARY");

                    b.HasIndex("ModelId1");

                    b.HasIndex(new[] { "CreatedBy" }, "fk_svc_user");

                    b.HasIndex(new[] { "VehicleId" }, "fk_svc_vehicle");

                    b.HasIndex(new[] { "SvcNo" }, "svc_no")
                        .IsUnique();

                    b.ToTable("service_orders", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("supplier_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("phone");

                    b.HasKey("SupplierId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Code" }, "code")
                        .IsUnique()
                        .HasDatabaseName("code2");

                    b.ToTable("suppliers", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("user_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("UserId"));

                    b.Property<bool?>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active")
                        .HasDefaultValueSql("'1'");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "username")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.Vehicle", b =>
                {
                    b.Property<long>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("vehicle_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("VehicleId"));

                    b.Property<DateTime?>("AcquiredAt")
                        .HasColumnType("datetime")
                        .HasColumnName("acquired_at");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("color");

                    b.Property<int?>("CurrentWarehouseId")
                        .HasColumnType("int(11)")
                        .HasColumnName("current_warehouse_id");

                    b.Property<string>("EngineNo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("engine_no");

                    b.Property<int>("ModelId")
                        .HasColumnType("int(11)")
                        .HasColumnName("model_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("vin");

                    b.Property<int?>("Year")
                        .HasColumnType("int(11)")
                        .HasColumnName("year");

                    b.HasKey("VehicleId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "EngineNo" }, "engine_no")
                        .IsUnique();

                    b.HasIndex(new[] { "CurrentWarehouseId" }, "fk_vehicles_wh");

                    b.HasIndex(new[] { "ModelId", "Color" }, "ix_vehicles_model_color");

                    b.HasIndex(new[] { "Status", "CurrentWarehouseId" }, "ix_vehicles_status_wh");

                    b.HasIndex(new[] { "Vin" }, "vin")
                        .IsUnique();

                    b.ToTable("vehicles", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.VehicleImage", b =>
                {
                    b.Property<long>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("image_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("ImageId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("kind");

                    b.Property<int?>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("sort_order")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<long>("VehicleId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("vehicle_id");

                    b.HasKey("ImageId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "VehicleId" }, "fk_vehicle_images_vehicle");

                    b.ToTable("vehicle_images", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.VehicleModel", b =>
                {
                    b.Property<int>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("model_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ModelId"));

                    b.Property<bool?>("Active")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active")
                        .HasDefaultValueSql("'1'");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)")
                        .HasColumnName("base_price");

                    b.Property<int>("BrandId")
                        .HasColumnType("int(11)")
                        .HasColumnName("brand_id");

                    b.Property<string>("FuelType")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("fuel_type");

                    b.Property<string>("ModelNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("model_no");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<int?>("SeatNo")
                        .HasColumnType("int(11)")
                        .HasColumnName("seat_no");

                    b.Property<string>("Specs")
                        .HasColumnType("json")
                        .HasColumnName("specs");

                    b.Property<string>("Transmission")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("transmission");

                    b.HasKey("ModelId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "BrandId" }, "fk_vehicle_models_brand");

                    b.HasIndex(new[] { "ModelNo" }, "model_no")
                        .IsUnique();

                    b.ToTable("vehicle_models", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.VehicleRegistration", b =>
                {
                    b.Property<long>("RegId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("reg_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("RegId"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Fields")
                        .HasColumnType("json")
                        .HasColumnName("fields");

                    b.Property<string>("OwnerName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("owner_name");

                    b.Property<DateOnly?>("RegDate")
                        .HasColumnType("date")
                        .HasColumnName("reg_date");

                    b.Property<string>("RegNo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("reg_no");

                    b.Property<long>("VehicleId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("vehicle_id");

                    b.HasKey("RegId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "VehicleId" }, "vehicle_id")
                        .IsUnique()
                        .HasDatabaseName("vehicle_id3");

                    b.ToTable("vehicle_registrations", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.Waitlist", b =>
                {
                    b.Property<int>("WaitlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("waitlist_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WaitlistId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.HasKey("WaitlistId")
                        .HasName("PRIMARY");

                    b.ToTable("waitlists", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.WaitlistEntry", b =>
                {
                    b.Property<long>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint(20)")
                        .HasColumnName("entry_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("EntryId"));

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("customer_id");

                    b.Property<int>("ModelId")
                        .HasColumnType("int(11)")
                        .HasColumnName("model_id");

                    b.Property<string>("PreferredColor")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("preferred_color");

                    b.Property<DateOnly?>("RequestedDate")
                        .HasColumnType("date")
                        .HasColumnName("requested_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("WaitlistId")
                        .HasColumnType("int(11)")
                        .HasColumnName("waitlist_id");

                    b.HasKey("EntryId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CustomerId" }, "fk_wle_customer");

                    b.HasIndex(new[] { "ModelId" }, "fk_wle_model");

                    b.HasIndex(new[] { "WaitlistId" }, "fk_wle_waitlist");

                    b.ToTable("waitlist_entries", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.Warehouse", b =>
                {
                    b.Property<int>("WarehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("warehouse_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WarehouseId"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.HasKey("WarehouseId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Code" }, "code")
                        .IsUnique()
                        .HasDatabaseName("code3");

                    b.ToTable("warehouses", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint(20)")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int(11)")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "RoleId" }, "fk_user_roles_role");

                    b.ToTable("user_roles", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("GoodsReturnItem", b =>
                {
                    b.HasOne("GoodsReturn", "GoodsReturn")
                        .WithMany("GoodsReturnItems")
                        .HasForeignKey("GrtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoodsReturn");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.Allotment", b =>
                {
                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.SalesOrder", "So")
                        .WithMany("Allotments")
                        .HasForeignKey("SoId")
                        .IsRequired()
                        .HasConstraintName("fk_allot_so");

                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.Vehicle", "Vehicle")
                        .WithOne("Allotment")
                        .HasForeignKey("ShowroomCar.Infrastructure.Persistence.Entities.Allotment", "VehicleId")
                        .IsRequired()
                        .HasConstraintName("fk_allot_vehicle");

                    b.Navigation("So");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.AuditLog", b =>
                {
                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.User", "ActorUser")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ActorUserId")
                        .HasConstraintName("fk_audit_user");

                    b.Navigation("ActorUser");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.Document", b =>
                {
                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.User", "CreatedByNavigation")
                        .WithMany("Documents")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("fk_doc_user");

                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.Customer", "Customer")
                        .WithMany("Documents")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("fk_doc_customer");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.DocumentLink", b =>
                {
                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.Document", "Doc")
                        .WithMany("DocumentLinks")
                        .HasForeignKey("DocId")
                        .IsRequired()
                        .HasConstraintName("fk_doclink_doc");

                    b.Navigation("Doc");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.GoodsReceipt", b =>
                {
                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.User", "CreatedByNavigation")
                        .WithMany("GoodsReceipts")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("fk_gr_user");

                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.PurchaseOrder", "Po")
                        .WithMany("GoodsReceipts")
                        .HasForeignKey("PoId")
                        .HasConstraintName("fk_gr_po");

                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.Warehouse", "Warehouse")
                        .WithMany("GoodsReceipts")
                        .HasForeignKey("WarehouseId")
                        .IsRequired()
                        .HasConstraintName("fk_gr_wh");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Po");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.GoodsReceiptItem", b =>
                {
                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.GoodsReceipt", "Gr")
                        .WithMany("GoodsReceiptItems")
                        .HasForeignKey("GrId")
                        .IsRequired()
                        .HasConstraintName("fk_gri_gr");

                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.Vehicle", "Vehicle")
                        .WithOne("GoodsReceiptItem")
                        .HasForeignKey("ShowroomCar.Infrastructure.Persistence.Entities.GoodsReceiptItem", "VehicleId")
                        .IsRequired()
                        .HasConstraintName("fk_gri_vehicle");

                    b.Navigation("Gr");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.InventoryMove", b =>
                {
                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.Warehouse", "FromWarehouse")
                        .WithMany("InventoryMoveFromWarehouses")
                        .HasForeignKey("FromWarehouseId")
                        .HasConstraintName("fk_inventory_moves_from_wh");

                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.User", "MovedByNavigation")
                        .WithMany("InventoryMoves")
                        .HasForeignKey("MovedBy")
                        .HasConstraintName("fk_inventory_moves_user");

                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.Warehouse", "ToWarehouse")
                        .WithMany("InventoryMoveToWarehouses")
                        .HasForeignKey("ToWarehouseId")
                        .HasConstraintName("fk_inventory_moves_to_wh");

                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.Vehicle", "Vehicle")
                        .WithMany("InventoryMoves")
                        .HasForeignKey("VehicleId")
                        .IsRequired()
                        .HasConstraintName("fk_inventory_moves_vehicle");

                    b.Navigation("FromWarehouse");

                    b.Navigation("MovedByNavigation");

                    b.Navigation("ToWarehouse");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.Invoice", b =>
                {
                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.User", "CreatedByNavigation")
                        .WithMany("Invoices")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("fk_inv_user");

                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("fk_inv_customer");

                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.SalesOrder", "So")
                        .WithMany("Invoices")
                        .HasForeignKey("SoId")
                        .HasConstraintName("fk_inv_so");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Customer");

                    b.Navigation("So");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.InvoiceItem", b =>
                {
                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.Invoice", "Invoice")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("InvoiceId")
                        .IsRequired()
                        .HasConstraintName("fk_invi_inv");

                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.Vehicle", "Vehicle")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("VehicleId")
                        .IsRequired()
                        .HasConstraintName("fk_invi_vehicle");

                    b.Navigation("Invoice");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.Payment", b =>
                {
                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.Customer", "Customer")
                        .WithMany("Payments")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("fk_pay_customer");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.PaymentAllocation", b =>
                {
                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.Invoice", "Invoice")
                        .WithMany("PaymentAllocations")
                        .HasForeignKey("InvoiceId")
                        .IsRequired()
                        .HasConstraintName("fk_alloc_invoice");

                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.Payment", "Payment")
                        .WithMany("PaymentAllocations")
                        .HasForeignKey("PaymentId")
                        .IsRequired()
                        .HasConstraintName("fk_alloc_pay");

                    b.Navigation("Invoice");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.PurchaseOrder", b =>
                {
                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.User", "CreatedByNavigation")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("fk_po_user");

                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.Supplier", "Supplier")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("SupplierId")
                        .IsRequired()
                        .HasConstraintName("fk_po_supplier");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.PurchaseOrderItem", b =>
                {
                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.VehicleModel", "Model")
                        .WithMany("PurchaseOrderItems")
                        .HasForeignKey("ModelId")
                        .IsRequired()
                        .HasConstraintName("fk_poi_model");

                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.PurchaseOrder", "Po")
                        .WithMany("PurchaseOrderItems")
                        .HasForeignKey("PoId")
                        .IsRequired()
                        .HasConstraintName("fk_poi_po");

                    b.Navigation("Model");

                    b.Navigation("Po");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.Quotation", b =>
                {
                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.User", "CreatedByNavigation")
                        .WithMany("Quotations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("fk_quote_user");

                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.Customer", "Customer")
                        .WithMany("Quotations")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("fk_quote_customer");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.QuotationItem", b =>
                {
                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.VehicleModel", "Model")
                        .WithMany("QuotationItems")
                        .HasForeignKey("ModelId")
                        .IsRequired()
                        .HasConstraintName("fk_qi_model");

                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.Quotation", "Quote")
                        .WithMany("QuotationItems")
                        .HasForeignKey("QuoteId")
                        .IsRequired()
                        .HasConstraintName("fk_qi_quote");

                    b.Navigation("Model");

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.SalesOrder", b =>
                {
                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.User", "AssignedToNavigation")
                        .WithMany("SalesOrderAssignedToNavigations")
                        .HasForeignKey("AssignedTo")
                        .HasConstraintName("fk_so_assigned_to");

                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.User", "CreatedByNavigation")
                        .WithMany("SalesOrderCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("fk_so_created_by");

                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.Customer", "Customer")
                        .WithMany("SalesOrders")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("fk_so_customer");

                    b.Navigation("AssignedToNavigation");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.SalesOrderItem", b =>
                {
                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.SalesOrder", "So")
                        .WithMany("SalesOrderItems")
                        .HasForeignKey("SoId")
                        .IsRequired()
                        .HasConstraintName("fk_soi_so");

                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.Vehicle", "Vehicle")
                        .WithOne("SalesOrderItem")
                        .HasForeignKey("ShowroomCar.Infrastructure.Persistence.Entities.SalesOrderItem", "VehicleId")
                        .IsRequired()
                        .HasConstraintName("fk_soi_vehicle");

                    b.Navigation("So");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.ServiceOrder", b =>
                {
                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.User", "CreatedByNavigation")
                        .WithMany("ServiceOrders")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("fk_svc_user");

                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.VehicleModel", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.Vehicle", "Vehicle")
                        .WithMany("ServiceOrders")
                        .HasForeignKey("VehicleId")
                        .IsRequired()
                        .HasConstraintName("fk_svc_vehicle");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Model");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.Vehicle", b =>
                {
                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.Warehouse", "CurrentWarehouse")
                        .WithMany("Vehicles")
                        .HasForeignKey("CurrentWarehouseId")
                        .HasConstraintName("fk_vehicles_wh");

                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.VehicleModel", "Model")
                        .WithMany("Vehicles")
                        .HasForeignKey("ModelId")
                        .IsRequired()
                        .HasConstraintName("fk_vehicles_model");

                    b.Navigation("CurrentWarehouse");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.VehicleImage", b =>
                {
                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.Vehicle", "Vehicle")
                        .WithMany("VehicleImages")
                        .HasForeignKey("VehicleId")
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_images_vehicle");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.VehicleModel", b =>
                {
                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.Brand", "Brand")
                        .WithMany("VehicleModels")
                        .HasForeignKey("BrandId")
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_models_brand");

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.VehicleRegistration", b =>
                {
                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.Vehicle", "Vehicle")
                        .WithOne("VehicleRegistration")
                        .HasForeignKey("ShowroomCar.Infrastructure.Persistence.Entities.VehicleRegistration", "VehicleId")
                        .IsRequired()
                        .HasConstraintName("fk_reg_vehicle");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.WaitlistEntry", b =>
                {
                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.Customer", "Customer")
                        .WithMany("WaitlistEntries")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("fk_wle_customer");

                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.VehicleModel", "Model")
                        .WithMany("WaitlistEntries")
                        .HasForeignKey("ModelId")
                        .IsRequired()
                        .HasConstraintName("fk_wle_model");

                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.Waitlist", "Waitlist")
                        .WithMany("WaitlistEntries")
                        .HasForeignKey("WaitlistId")
                        .IsRequired()
                        .HasConstraintName("fk_wle_waitlist");

                    b.Navigation("Customer");

                    b.Navigation("Model");

                    b.Navigation("Waitlist");
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_role");

                    b.HasOne("ShowroomCar.Infrastructure.Persistence.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_user");
                });

            modelBuilder.Entity("GoodsReturn", b =>
                {
                    b.Navigation("GoodsReturnItems");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.Brand", b =>
                {
                    b.Navigation("VehicleModels");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.Customer", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Invoices");

                    b.Navigation("Payments");

                    b.Navigation("Quotations");

                    b.Navigation("SalesOrders");

                    b.Navigation("WaitlistEntries");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.Document", b =>
                {
                    b.Navigation("DocumentLinks");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.GoodsReceipt", b =>
                {
                    b.Navigation("GoodsReceiptItems");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.Invoice", b =>
                {
                    b.Navigation("InvoiceItems");

                    b.Navigation("PaymentAllocations");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.Payment", b =>
                {
                    b.Navigation("PaymentAllocations");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.PurchaseOrder", b =>
                {
                    b.Navigation("GoodsReceipts");

                    b.Navigation("PurchaseOrderItems");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.Quotation", b =>
                {
                    b.Navigation("QuotationItems");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.SalesOrder", b =>
                {
                    b.Navigation("Allotments");

                    b.Navigation("Invoices");

                    b.Navigation("SalesOrderItems");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.Supplier", b =>
                {
                    b.Navigation("PurchaseOrders");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Documents");

                    b.Navigation("GoodsReceipts");

                    b.Navigation("InventoryMoves");

                    b.Navigation("Invoices");

                    b.Navigation("PurchaseOrders");

                    b.Navigation("Quotations");

                    b.Navigation("SalesOrderAssignedToNavigations");

                    b.Navigation("SalesOrderCreatedByNavigations");

                    b.Navigation("ServiceOrders");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.Vehicle", b =>
                {
                    b.Navigation("Allotment");

                    b.Navigation("GoodsReceiptItem");

                    b.Navigation("InventoryMoves");

                    b.Navigation("InvoiceItems");

                    b.Navigation("SalesOrderItem");

                    b.Navigation("ServiceOrders");

                    b.Navigation("VehicleImages");

                    b.Navigation("VehicleRegistration");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.VehicleModel", b =>
                {
                    b.Navigation("PurchaseOrderItems");

                    b.Navigation("QuotationItems");

                    b.Navigation("Vehicles");

                    b.Navigation("WaitlistEntries");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.Waitlist", b =>
                {
                    b.Navigation("WaitlistEntries");
                });

            modelBuilder.Entity("ShowroomCar.Infrastructure.Persistence.Entities.Warehouse", b =>
                {
                    b.Navigation("GoodsReceipts");

                    b.Navigation("InventoryMoveFromWarehouses");

                    b.Navigation("InventoryMoveToWarehouses");

                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
